### ISSUE TITLE
无法与其他软件导出的抽卡记录合并

### ISSUE THREAD

**Issue by FuckBound** [cntvc/Genshin-Impact-Tools#69]
### 系统版本 (System Version)

Windows10 or Windows11

### 软件版本 (Software version)

0.1.8

### 发生了什么？ (What happened?)

无法合并抽卡记录.
![image](https://user-images.githubusercontent.com/59684700/226620405-29697ee4-c05d-4516-ab01-4b517935cb70.png)
question: 与其他软件(LittlePaimon)导出的抽卡记录合并时,只会生成包含本软件的抽卡记录.

复现
[merge.zip](https://github.com/cntvc/Genshin-Impact-Tools/files/11028804/merge.zip)

**Comment by cntvc** [comment]
感谢反馈。
原因是对于 `UIGF` 格式校验逻辑存在问题，导致该文件识别为无效数据文件。

**Comment by cntvc** [comment]
0.1.9 版本已修复
